// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RI.api.Data;

namespace RI.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200611192659_VideoPlusUserEntity")]
    partial class VideoPlusUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("RI.api.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("passwordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("passwordSalt")
                        .HasColumnType("BLOB");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RI.api.Models.Video", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<double>("dislikeCount")
                        .HasColumnType("REAL");

                    b.Property<double>("likeCount")
                        .HasColumnType("REAL");

                    b.Property<string>("submittedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("submittedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("submittedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("views")
                        .HasColumnType("INTEGER");

                    b.Property<string>("youtubeId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
